version: '3.7'
services:
  app:
    container_name: typescript_udemy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app:rw
    ports:
      - '3005:3000'
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks: 
      - internal  

networks:
  internal:
    driver: bridge 